site_name: Jebasa Documentation
site_description: Japanese ebook audio subtitle aligner - Create synchronized subtitles from Japanese audiobooks and EPUB files
site_url: https://jebasa.readthedocs.io
repo_name: OCboy5/jebasa
repo_url: https://github.com/OCboy5/jebasa

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user-guide.md
  - Examples: examples.md
  - API Reference: api-reference.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OCboy5/jebasa
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jebasa/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

watch:
  - src/jebasa
